services:
  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      - 'MYSQL_DATABASE=belajar_spring'
      - 'MYSQL_PASSWORD='
      - 'MYSQL_ROOT_PASSWORD='
      - 'MYSQL_USER=root'
    ports:
      - '3306'
